/*

 SRC/GBC.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define gbcBank 0

/* Super Gameboy palette 0 */
#define gbcSGBPal0c0 6076
#define gbcSGBPal0c1 8935
#define gbcSGBPal0c2 6596
#define gbcSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define gbcSGBPal1c0 6076
#define gbcSGBPal1c1 8935
#define gbcSGBPal1c2 6596
#define gbcSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define gbcSGBPal2c0 6076
#define gbcSGBPal2c1 8935
#define gbcSGBPal2c2 6596
#define gbcSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define gbcSGBPal3c0 6076
#define gbcSGBPal3c1 8935
#define gbcSGBPal3c2 6596
#define gbcSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define gbcCGBPal0c0 6076
#define gbcCGBPal0c1 8935
#define gbcCGBPal0c2 6596
#define gbcCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define gbcCGBPal1c0 6076
#define gbcCGBPal1c1 8935
#define gbcCGBPal1c2 6596
#define gbcCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define gbcCGBPal2c0 6076
#define gbcCGBPal2c1 32767
#define gbcCGBPal2c2 29280
#define gbcCGBPal2c3 0

/* Gameboy Color palette 3 */
#define gbcCGBPal3c0 6076
#define gbcCGBPal3c1 8935
#define gbcCGBPal3c2 6596
#define gbcCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define gbcCGBPal4c0 6076
#define gbcCGBPal4c1 8935
#define gbcCGBPal4c2 6596
#define gbcCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define gbcCGBPal5c0 6076
#define gbcCGBPal5c1 8935
#define gbcCGBPal5c2 6596
#define gbcCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define gbcCGBPal6c0 6076
#define gbcCGBPal6c1 8935
#define gbcCGBPal6c2 6596
#define gbcCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define gbcCGBPal7c0 6076
#define gbcCGBPal7c1 8935
#define gbcCGBPal7c2 6596
#define gbcCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char gbcCGB[];
/* Start of tile array. */
extern unsigned char gbc[];

/* End of SRC/GBC.H */
