/*

 HALU.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define haluBank 0

/* Super Gameboy palette 0 */
#define haluSGBPal0c0 6076
#define haluSGBPal0c1 8935
#define haluSGBPal0c2 6596
#define haluSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define haluSGBPal1c0 6076
#define haluSGBPal1c1 8935
#define haluSGBPal1c2 6596
#define haluSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define haluSGBPal2c0 6076
#define haluSGBPal2c1 8935
#define haluSGBPal2c2 6596
#define haluSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define haluSGBPal3c0 6076
#define haluSGBPal3c1 8935
#define haluSGBPal3c2 6596
#define haluSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define haluCGBPal0c0 0
#define haluCGBPal0c1 32767
#define haluCGBPal0c2 20009
#define haluCGBPal0c3 24239

/* Gameboy Color palette 1 */
#define haluCGBPal1c0 6076
#define haluCGBPal1c1 8935
#define haluCGBPal1c2 6596
#define haluCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define haluCGBPal2c0 6076
#define haluCGBPal2c1 8935
#define haluCGBPal2c2 6596
#define haluCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define haluCGBPal3c0 6076
#define haluCGBPal3c1 8935
#define haluCGBPal3c2 6596
#define haluCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define haluCGBPal4c0 6076
#define haluCGBPal4c1 8935
#define haluCGBPal4c2 6596
#define haluCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define haluCGBPal5c0 6076
#define haluCGBPal5c1 8935
#define haluCGBPal5c2 6596
#define haluCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define haluCGBPal6c0 6076
#define haluCGBPal6c1 8935
#define haluCGBPal6c2 6596
#define haluCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define haluCGBPal7c0 6076
#define haluCGBPal7c1 8935
#define haluCGBPal7c2 6596
#define haluCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char haluCGB[];
/* Start of tile array. */
extern unsigned char halu[];

/* End of HALU.H */
