/*

 STARS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 32 x 32
  Tiles                : 0 to 1

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define starsBank 0

/* Super Gameboy palette 0 */
#define starsSGBPal0c0 6076
#define starsSGBPal0c1 8935
#define starsSGBPal0c2 6596
#define starsSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define starsSGBPal1c0 6076
#define starsSGBPal1c1 8935
#define starsSGBPal1c2 6596
#define starsSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define starsSGBPal2c0 6076
#define starsSGBPal2c1 8935
#define starsSGBPal2c2 6596
#define starsSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define starsSGBPal3c0 6076
#define starsSGBPal3c1 8935
#define starsSGBPal3c2 6596
#define starsSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define starsCGBPal0c0 0
#define starsCGBPal0c1 32767
#define starsCGBPal0c2 20009
#define starsCGBPal0c3 24239

/* Gameboy Color palette 1 */
#define starsCGBPal1c0 0
#define starsCGBPal1c1 32767
#define starsCGBPal1c2 28361
#define starsCGBPal1c3 32557

/* Gameboy Color palette 2 */
#define starsCGBPal2c0 6076
#define starsCGBPal2c1 8935
#define starsCGBPal2c2 6596
#define starsCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define starsCGBPal3c0 6076
#define starsCGBPal3c1 8935
#define starsCGBPal3c2 6596
#define starsCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define starsCGBPal4c0 6076
#define starsCGBPal4c1 8935
#define starsCGBPal4c2 6596
#define starsCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define starsCGBPal5c0 6076
#define starsCGBPal5c1 8935
#define starsCGBPal5c2 6596
#define starsCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define starsCGBPal6c0 6076
#define starsCGBPal6c1 8935
#define starsCGBPal6c2 6596
#define starsCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define starsCGBPal7c0 6076
#define starsCGBPal7c1 8935
#define starsCGBPal7c2 6596
#define starsCGBPal7c3 5344
/* CGBpalette entries. */
extern unsigned char starsCGB[];
/* Start of tile array. */
extern unsigned char stars[];

/* End of STARS.H */
